version: "3.7"
services:
  postgres_db:
    image: postgres:13
    environment:
      POSTGRES_USER: tetris
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: tetris
    ports:
      - 5434:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data