name: Test Application

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]

jobs:
  frontend-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
          cache-dependency-path: |
            frontend/yarn.lock
            acceptance/yarn.lock
      - run: cd frontend && yarn install && yarn test
  backend-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Setup fake build dir && test
        run: cd backend/server && mkdir build && touch build/index.html && cd .. && go test -v ./...
  acceptance-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
          cache-dependency-path: |
            frontend/yarn.lock
            acceptance/yarn.lock
      - name: Test
        run: cd frontend && yarn install && cd ../acceptance && yarn install && yarn test
