name: Test Application

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      tetris_db:
        image: postgres
        env:
          POSTGRES_PASSWORD: tetris_test
          POSTGRES_USER: tetris_test
          POSTGRES_DB: tetris_test
        ports:
          - 5433:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: cd frontend
      - run: yarn test