name: Test Application

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]

jobs:
  frontend-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - run: cd frontend && yarn install && yarn test